### ISSUE TITLE
An error occurred and looking forward to your help

### ISSUE THREAD

**Issue by yqwang0374** [Shi-Qi-Li/DBDNet#1]
Hello, your work is very innovative and I am very interested. But when attempting to run your publicly available code, an error occurred. I hope to receive your help. thank you.

error location：
When in the second stage of training (Train the registration model): python train.py -- config modelnet40.yaml, an error occurs: FileNotFoundError: [Errno 2] No such file or directory: 'ckpt/modelnet40_overap.noise. py'

Attempt to solve：
When I tried to change the overlap retrieval kpt: ckpt/modelnet40_overlap noise.py in DBDNet_paper/config/modelnet40.yaml to DBDNet_paper/exp/modelnet40_overlap noise/2024-06-26-22:41:27/checkpoints/epoch_100.pth, I still reported an error. The error message is: loss ["loss"]. backward()  RuntimeError: Function 'LinalgSvdBackward0' returned nan values in its 0th output.

Looking forward to your early reply.

**Comment by Shi-Qi-Li** [comment]
> Hello, your work is very innovative and I am very interested. But when attempting to run your publicly available code, an error occurred. I hope to receive your help. thank you.
> 
> error location： When in the second stage of training (Train the registration model): python train.py -- config modelnet40.yaml, an error occurs: FileNotFoundError: [Errno 2] No such file or directory: 'ckpt/modelnet40_overap.noise. py'
> 
> Attempt to solve： When I tried to change the overlap retrieval kpt: ckpt/modelnet40_overlap noise.py in DBDNet_paper/config/modelnet40.yaml to DBDNet_paper/exp/modelnet40_overlap noise/2024-06-26-22:41:27/checkpoints/epoch_100.pth, I still reported an error. The error message is: loss ["loss"]. backward() RuntimeError: Function 'LinalgSvdBackward0' returned nan values in its 0th output.
> 
> Looking forward to your early reply.

Hi @WYQ0374 
Thanks for your interests. There is a typo about the extension of checkpoint path, it should be .pth rather than .py. I have fixed the issue in a new commit, thank you for pointing out it. And the 2nd stage training is indeed a little unstable, maybe you can slightly adjust the learning rate in your experiment, I think it will not bring a large difference.

**Comment by yqwang0374** [comment]
Thank you for your prompt reply. I would greatly appreciate it.
My remaining question is that the first stage of training did not generate the file (ckpt/modelnet40-overlap-noise. pth), making it impossible to proceed with the second stage of training. So, how to generate this file? Thank you for your help.

**Comment by Shi-Qi-Li** [comment]
> Thank you for your prompt reply. I would greatly appreciate it. My remaining question is that the first stage of training did not generate the file (ckpt/modelnet40-overlap-noise. pth), making it impossible to proceed with the second stage of training. So, how to generate this file? Thank you for your help.

Actually the 1st stage did not generate the file, I just rename the best checkpoint from epoch-xx.pth to modelnet40-overlap-noise.pth for better management during the release. So your initial attempt about change the config file is correct.

**Comment by yqwang0374** [comment]
Thank you for your help, and I wish you all the best in your research.
---- Replied Message ----
FromShiqi ***@***.***>Date06/30/2024 16:32 ***@***.***> ***@***.***>,
***@***.***>SubjectRe: [Shi-Qi-Li/DBDNet] An error occurred and looking forward to your help (Issue #1)
Thank you for your prompt reply. I would greatly appreciate it. My remaining question is that the first stage of training did not generate the file (ckpt/modelnet40-overlap-noise. pth), making it impossible to proceed with the second stage of training. So, how to generate this file? Thank you for your help.
Actually the 1st stage did not generate the file, I just rename the best checkpoint from epoch-xx.pth to modelnet40-overlap-noise.pth for better management during the release. So your initial attempt about change the config file is correct.

**Comment by yqwang0374** [comment]
hello, I have a question that I would like to ask you.

During the 2nd stage of training, the following errors always occur:【  File "/home/wangyongqiang/miniconda3/envs/dbd2/lib/python3.9/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function 'LinalgSvdBackward0' returned nan values in its 0th output.】
![image](https://github.com/Shi-Qi-Li/DBDNet/assets/74130749/ea197eee-bfa0-4495-805d-5b1936e7e397)


Attempting a solution:
When commenting out the following code (train.py   torch. autorad. set_detect-anomaly (True))
This error will occur again: U, S, V=torch. svd (H, some=False)
torch._C._LinAlgError: cusolver error: CUSOLVER_STATUS_EXECUTION_FAILED, when calling `cusolverDnSgesvd( handle, jobu, jobvt, m, n, A, lda, S, U, ldu, VT, ldvt, work, lwork, rwork, info)`. This error may appear if the input matrix contains NaN.】
![image](https://github.com/Shi-Qi-Li/DBDNet/assets/74130749/d11c39f2-5768-442d-bb26-d5d344f7c7d6)

Requesting your help. thank you

**Comment by Shi-Qi-Li** [comment]
> hello, I have a question that I would like to ask you.
> 
> During the 2nd stage of training, the following errors always occur:【 File "/home/wangyongqiang/miniconda3/envs/dbd2/lib/python3.9/site-packages/torch/autograd/**init**.py", line 173, in backward Variable._execution_engine.run_backward( # Calls into the C++ engine to run the backward pass RuntimeError: Function 'LinalgSvdBackward0' returned nan values in its 0th output.】 ![image](https://private-user-images.githubusercontent.com/74130749/344690295-ea197eee-bfa0-4495-805d-5b1936e7e397.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NDgxMzQsIm5iZiI6MTcxOTg0NzgzNCwicGF0aCI6Ii83NDEzMDc0OS8zNDQ2OTAyOTUtZWExOTdlZWUtYmZhMC00NDk1LTgwNWQtNWIxOTM2ZTdlMzk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDE1MzAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkZmQyMTA3YjVkNGRlMzA5MDAzYjMzNWVkOTZiNDY1OWY2MjE3YWU4ODIwNWJmMjYxZjFlNmU0YjQ2Y2MzOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xlP39Xbu_RAkurhAqh1uf4jCS4aZv4AxSqzjlX-TGrM)
> 
> Attempting a solution: When commenting out the following code (train.py torch. autorad. set_detect-anomaly (True)) This error will occur again: U, S, V=torch. svd (H, some=False) torch._C._LinAlgError: cusolver error: CUSOLVER_STATUS_EXECUTION_FAILED, when calling `cusolverDnSgesvd( handle, jobu, jobvt, m, n, A, lda, S, U, ldu, VT, ldvt, work, lwork, rwork, info)`. This error may appear if the input matrix contains NaN.】 ![image](https://private-user-images.githubusercontent.com/74130749/344691674-d11c39f2-5768-442d-bb26-d5d344f7c7d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NDgxMzQsIm5iZiI6MTcxOTg0NzgzNCwicGF0aCI6Ii83NDEzMDc0OS8zNDQ2OTE2NzQtZDExYzM5ZjItNTc2OC00NDJkLWJiMjYtZDVkMzQ0ZjdjN2Q2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDE1MzAzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzOGE2Mzc0ZDk3NmUyODg2MDgzMDNlYzdlODkwNzgyZjA3ZjRmODhkYzNiMmU0ZDE0Y2Q0ODk5MDQ4MjdjZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wtRqSTy67lhLe6dpeVWOYBmdHkclf58ulEK0dX6v_VI)
> 
> Requesting your help. thank you

I think it might be helpful to first check whether the tensor corresponding to the source and target point clouds after overlap selection contains nan.
