### ISSUE TITLE
3DMatch_overlap_info.pkl file missing

### ISSUE THREAD

**Issue by awordx** [Shi-Qi-Li/DBDNet#2]
![Snipaste_2024-08-16_19-35-57](https://github.com/user-attachments/assets/7412ca0f-14e8-4920-997c-8f312a4d04e3)
First of all, thank you very much for your outstanding contribution to this. When I was training the overlap model using python train.py --config config/3dmatch_overlap.yaml, I found that the 3DMatch_overlap_info.pkl file was missing. I couldn't find it anywhere. Could it be that you forgot to upload this file? I apologize for the trouble.

**Comment by Shi-Qi-Li** [comment]
> ![Snipaste_2024-08-16_19-35-57](https://private-user-images.githubusercontent.com/59833754/358570036-7412ca0f-14e8-4920-997c-8f312a4d04e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4MDg4ODUsIm5iZiI6MTcyMzgwODU4NSwicGF0aCI6Ii81OTgzMzc1NC8zNTg1NzAwMzYtNzQxMmNhMGYtMTRlOC00OTIwLTk5N2MtOGYzMTJhNGQwNGUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDExNDMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwMzliODU0N2VlMTRjMDAyZjRmNTg5ZTI3M2Y3MDg2OWJiOTk1YjcwN2QyMzVkNmJiZmZkNDA4NzZhOGQ2YTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DOkpT0Tuw6oEf3eYkRJLd9MbNHPFsHKBzp2ZBq5f_H4) First of all, thank you very much for your outstanding contribution to this. When I was training the overlap model using python train.py --config config/3dmatch_overlap.yaml, I found that the 3DMatch_overlap_info.pkl file was missing. I couldn't find it anywhere. Could it be that you forgot to upload this file? I apologize for the trouble.

Thanks for your interest! This file is generated by the last step in [data preparation](https://github.com/Shi-Qi-Li/DBDNet#data-preparation), have you followed this step?

**Comment by awordx** [comment]
Sorry, I missed that line. I'll go ahead and generate it. Thank you.
